### PR TITLE
Filtering bugfix

### PR DESCRIPTION
**Pull request by wisd0me**

### CODE REVIEW

**Comment by dkerr64** [comment]
okay, so basically you found and fixed a memory leak.  Correct?  That made me look through the rest of the file and I found that the same problem may exist here... https://github.com/dkerr64/avahi/blob/6dabb000cc4206ecbf30d016c0a4625c5eae2930/avahi-core/server.c#L1203
do you agree?
Also, I was always taught that goto's were to be avoided as much as possible.  But I do see it used elsewhere in this file for the same reasons... though they use the label "fail" so I'm wondering if to use that instead of "unref" for consistency.

**Comment by wisd0me** [comment]
> so basically you found and fixed a memory leak. Correct?

Yeah, but not only the leak - as I've described in the commit message, there was a bug which lead to completely incorrect behaviour in my case with macbook - services was not discovered at all, if the whitelisted service record came not at the first place in the DNS response!  

Let's say you configured `reflect-filters=_smb._tcp` and using avahi without proposed fix:
```
this response will be droped:
| mylaptop._sftp-ssh._tcp | mylaptop._smb._tcp |
```
```
this response will pass:
| mylaptop._smb._tcp | 
```

> That made me look through the rest of the file and I found that the same problem may exist here... 

Looks like the same problem to me.

> though they use the label "fail" so I'm wondering if to use that instead of "unref" for consistency.

It would be wrong to use "fail" in this code, 'cause it's not a failure if we didn't match some record in the response, we'll just skip it and go further, so I presume It's a legitimate "inconsistency", so to say.

**Comment by dkerr64** [comment]
Thank you @wisd0me I have merged your fix and also fixed the other memory leak in the same file.  I also first brought my fork up-to-date with upstream master.  I continue to hope that @lathiat will merge the filter function into his master.

**Comment by wisd0me** [comment]
Good luck with upstream, hope this will be merged evetually!

**Pull request merged**
